pipeline {
  agent any
  stages {
    stage('aws and eksctl version') {
      steps {
        withAWS(region:'us-east-2', credentials:'eks-docker-hub') {
          sh 'aws --version'
          sh 'eksctl version'
        }
      }
    }
  }
}
